name: Build DIE-engine

on:
  workflow_dispatch:

jobs:
  build-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
         submodules: 'recursive'
         path: 'code'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev qtscript5-dev qttools5-dev-tools libqt5svg5-dev git build-essential -y
          sudo apt-get install qtchooser qt5-qmake -y

      - name: Build
        run: |
          cd code
          bash -x build_dpkg.sh

  build-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
         submodules: 'recursive'
         path: 'code'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev qtscript5-dev qttools5-dev-tools libqt5svg5-dev git build-essential -y
          sudo apt-get install qtchooser qt5-qmake -y

      - name: Build
        run: |
          cd code
          bash -x build_dpkg.sh

  build-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
         submodules: 'recursive'
         path: 'code'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          #dir: ${{ github.workspace }}

      - name: Build
        run: |
          cd code
          bash -x build_mac.sh

  build-windows-32:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
         submodules: 'recursive'
         path: 'code'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86
          vs-version: '[16.0,17.0)'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_msvc2019'
          dir: ${{ github.workspace }}

      - name: Setup environment variables and run build script
        shell: cmd
        run: |
          cd code
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
         
          set VSVARS_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
          set QMAKE_PATH="${{ github.workspace }}\Qt\5.15.2\msvc2019\bin\qmake.exe"
          set SEVENZIP_PATH="C:\Program Files\7-Zip\7z.exe"
          set INNOSETUP_PATH="C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          set X_BUILD_PREFIX="win32"
          set X_SOURCE_PATH="${{ github.workspace }}\code"
          for /f "delims=" %%x in ('type "%X_SOURCE_PATH%\release_version.txt"') do set X_RELEASE_VERSION=%%x
          call "%X_SOURCE_PATH%\build_win_generic.cmd"
          
  build-windows-64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
         submodules: 'recursive'
         path: 'code'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          vs-version: '[16.0,17.0)'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: ${{ github.workspace }}

      - name: Setup environment variables and run build script
        shell: cmd
        run: |
          cd code
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

          set VSVARS_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
          set QMAKE_PATH="${{ github.workspace }}\Qt\5.15.2\msvc2019_64\bin\qmake.exe"
          set SEVENZIP_PATH="C:\Program Files\7-Zip\7z.exe"
          set INNOSETUP_PATH="C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          set X_BUILD_PREFIX="win64"
          set X_SOURCE_PATH="${{ github.workspace }}\code"
          for /f "delims=" %%x in ('type "%X_SOURCE_PATH%\release_version.txt"') do set X_RELEASE_VERSION=%%x
          call "%X_SOURCE_PATH%\build_win_generic.cmd"
