name: Build DIE-engine tmp

on:
  workflow_dispatch:
  release:
    types: [created]
  schedule:
    - cron: '0 0 * * MON'

env:
  SRC_PATH: ${{ github.workspace }}/src
  SRC_PATH_WIN: ${{ github.workspace }}\src
  RELEASE_PATH: ${{ github.workspace }}/src/release

# The jobs are based on the official build notes:
# https://github.com/horsicq/Detect-It-Easy/blob/master/docs/BUILD.md

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.10, ubuntu-25.04, ubuntu-25.10]
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: ${{ env.SRC_PATH }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qtbase5-dev \
            qtscript5-dev \
            qttools5-dev-tools \
            libqt5svg5-dev \
            qtchooser \
            qt5-qmake \
            build-essential

      - name: Build .deb package
        working-directory: ${{ env.SRC_PATH }}
        run: bash -x build_dpkg.sh

      - name: Upload .deb to Release
        uses: softprops/action-gh-release@v2
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: Beta
          draft: false
          prerelease: true
          files: ${{ env.RELEASE_PATH }}/*.deb
